import "@girs/gio-2.0"
import "@girs/meta-13"
import "@girs/shell-13"
import "@girs/gjs"
import "@girs/gjs/ambient"
import "@girs/gjs/dom"
import "@girs/gnome-shell/extensions/extension"
// import "@girs/gnome-shell/dist/index"
// import "@girs/gnome-shell/dist/index-ambient"
import "@girs/gnome-shell/dist/ui"